modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "field_moves"
version = "1.5-forge-1.0.0"
displayName = "Cobblemon Field Moves"
description = '''
Adds the in-world effects of field moves and abilities to Cobblemon.
'''

[[dependencies.field_moves]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.field_moves]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.field_moves]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.0,1.6.0)"
ordering = "NONE"
side = "BOTH"
